import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import { AuthProvider } from "@/contexts/AuthContext";

import "./globals.css";
import Navigation from "./components/navigation";
import Footer from "./components/footer";
// import { ThemeProvider } from "./components/theme-provider";

const nunitoSans = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  //WITH antialiased:      text looks smooth and crisp
  return (
    <html
      lang="en"
      className={`${nunitoSans.className}`} // ✅ FIXED!
      suppressHydrationWarning
    >
      <body className={`${nunitoSans.variable} antialiased`}>
        <AuthProvider>
          <Navigation />
          <main className="flex-1 container mx-auto p-6"> {children}</main>
        </AuthProvider>

        <Footer />
      </body>
    </html>
  );
}
